name: Build APK

on:
  repository_dispatch:
    types: [build-apk, build_apk]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Receive Data
        run: |
          echo "App URL: ${{ github.event.client_payload.appUrl }}"
          echo "Doc ID: ${{ github.event.client_payload.docId }}"
          
      - name: Build APK (Simulation)
        run: |
          echo "Simulating APK Generation..."
          sleep 15
          
      - name: Update Firebase Database
        run: |
          PROJECT_ID="my-app-ae88f"
          DOC_ID="${{ github.event.client_payload.docId }}"
          API_KEY="AIzaSyAo9ddKYbaCiIz5iwCNJN0pxs3UQvBvrTI"
          
          if [ -z "$DOC_ID" ] || [ "$DOC_ID" == "null" ]; then
            echo "Error: DOC_ID is empty! App failed to send data."
            exit 1
          fi
          
          curl -X PATCH "https://firestore.googleapis.com/v1/projects/$PROJECT_ID/databases/(default)/documents/apk_builds/$DOC_ID?key=$API_KEY&updateMask.fieldPaths=status&updateMask.fieldPaths=downloadUrl" \
          -H "Content-Type: application/json" \
          -d '{
            "fields": {
              "status": { "stringValue": "completed" },
              "downloadUrl": { "stringValue": "https://example.com/download/app.apk" }
            }
          }'
